package org.heminjian.mybatis_generator.entity;

import java.util.Date;

public class AlertLevelStatistics {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_level_statistics.id
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_level_statistics.dev
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    private String dev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_level_statistics.count_time
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    private Date countTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_level_statistics.level_0_sum
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    private Integer level0Sum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_level_statistics.level_1_sum
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    private Integer level1Sum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_level_statistics.level_2_sum
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    private Integer level2Sum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_level_statistics.level_3_sum
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    private Integer level3Sum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_level_statistics.level_4_sum
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    private Integer level4Sum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_level_statistics.count_type
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    private String countType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_level_statistics.id
     *
     * @return the value of alert_level_statistics.id
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_level_statistics.id
     *
     * @param id the value for alert_level_statistics.id
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_level_statistics.dev
     *
     * @return the value of alert_level_statistics.dev
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public String getDev() {
        return dev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_level_statistics.dev
     *
     * @param dev the value for alert_level_statistics.dev
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public void setDev(String dev) {
        this.dev = dev == null ? null : dev.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_level_statistics.count_time
     *
     * @return the value of alert_level_statistics.count_time
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public Date getCountTime() {
        return countTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_level_statistics.count_time
     *
     * @param countTime the value for alert_level_statistics.count_time
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public void setCountTime(Date countTime) {
        this.countTime = countTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_level_statistics.level_0_sum
     *
     * @return the value of alert_level_statistics.level_0_sum
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public Integer getLevel0Sum() {
        return level0Sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_level_statistics.level_0_sum
     *
     * @param level0Sum the value for alert_level_statistics.level_0_sum
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public void setLevel0Sum(Integer level0Sum) {
        this.level0Sum = level0Sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_level_statistics.level_1_sum
     *
     * @return the value of alert_level_statistics.level_1_sum
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public Integer getLevel1Sum() {
        return level1Sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_level_statistics.level_1_sum
     *
     * @param level1Sum the value for alert_level_statistics.level_1_sum
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public void setLevel1Sum(Integer level1Sum) {
        this.level1Sum = level1Sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_level_statistics.level_2_sum
     *
     * @return the value of alert_level_statistics.level_2_sum
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public Integer getLevel2Sum() {
        return level2Sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_level_statistics.level_2_sum
     *
     * @param level2Sum the value for alert_level_statistics.level_2_sum
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public void setLevel2Sum(Integer level2Sum) {
        this.level2Sum = level2Sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_level_statistics.level_3_sum
     *
     * @return the value of alert_level_statistics.level_3_sum
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public Integer getLevel3Sum() {
        return level3Sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_level_statistics.level_3_sum
     *
     * @param level3Sum the value for alert_level_statistics.level_3_sum
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public void setLevel3Sum(Integer level3Sum) {
        this.level3Sum = level3Sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_level_statistics.level_4_sum
     *
     * @return the value of alert_level_statistics.level_4_sum
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public Integer getLevel4Sum() {
        return level4Sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_level_statistics.level_4_sum
     *
     * @param level4Sum the value for alert_level_statistics.level_4_sum
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public void setLevel4Sum(Integer level4Sum) {
        this.level4Sum = level4Sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_level_statistics.count_type
     *
     * @return the value of alert_level_statistics.count_type
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public String getCountType() {
        return countType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_level_statistics.count_type
     *
     * @param countType the value for alert_level_statistics.count_type
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public void setCountType(String countType) {
        this.countType = countType == null ? null : countType.trim();
    }
}