package org.heminjian.mybatis_generator.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AlertLevelStatisticsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alert_level_statistics
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alert_level_statistics
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alert_level_statistics
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_level_statistics
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public AlertLevelStatisticsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_level_statistics
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_level_statistics
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_level_statistics
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_level_statistics
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_level_statistics
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_level_statistics
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_level_statistics
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_level_statistics
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_level_statistics
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_level_statistics
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table alert_level_statistics
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDevIsNull() {
            addCriterion("dev is null");
            return (Criteria) this;
        }

        public Criteria andDevIsNotNull() {
            addCriterion("dev is not null");
            return (Criteria) this;
        }

        public Criteria andDevEqualTo(String value) {
            addCriterion("dev =", value, "dev");
            return (Criteria) this;
        }

        public Criteria andDevNotEqualTo(String value) {
            addCriterion("dev <>", value, "dev");
            return (Criteria) this;
        }

        public Criteria andDevGreaterThan(String value) {
            addCriterion("dev >", value, "dev");
            return (Criteria) this;
        }

        public Criteria andDevGreaterThanOrEqualTo(String value) {
            addCriterion("dev >=", value, "dev");
            return (Criteria) this;
        }

        public Criteria andDevLessThan(String value) {
            addCriterion("dev <", value, "dev");
            return (Criteria) this;
        }

        public Criteria andDevLessThanOrEqualTo(String value) {
            addCriterion("dev <=", value, "dev");
            return (Criteria) this;
        }

        public Criteria andDevLike(String value) {
            addCriterion("dev like", value, "dev");
            return (Criteria) this;
        }

        public Criteria andDevNotLike(String value) {
            addCriterion("dev not like", value, "dev");
            return (Criteria) this;
        }

        public Criteria andDevIn(List<String> values) {
            addCriterion("dev in", values, "dev");
            return (Criteria) this;
        }

        public Criteria andDevNotIn(List<String> values) {
            addCriterion("dev not in", values, "dev");
            return (Criteria) this;
        }

        public Criteria andDevBetween(String value1, String value2) {
            addCriterion("dev between", value1, value2, "dev");
            return (Criteria) this;
        }

        public Criteria andDevNotBetween(String value1, String value2) {
            addCriterion("dev not between", value1, value2, "dev");
            return (Criteria) this;
        }

        public Criteria andCountTimeIsNull() {
            addCriterion("count_time is null");
            return (Criteria) this;
        }

        public Criteria andCountTimeIsNotNull() {
            addCriterion("count_time is not null");
            return (Criteria) this;
        }

        public Criteria andCountTimeEqualTo(Date value) {
            addCriterion("count_time =", value, "countTime");
            return (Criteria) this;
        }

        public Criteria andCountTimeNotEqualTo(Date value) {
            addCriterion("count_time <>", value, "countTime");
            return (Criteria) this;
        }

        public Criteria andCountTimeGreaterThan(Date value) {
            addCriterion("count_time >", value, "countTime");
            return (Criteria) this;
        }

        public Criteria andCountTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("count_time >=", value, "countTime");
            return (Criteria) this;
        }

        public Criteria andCountTimeLessThan(Date value) {
            addCriterion("count_time <", value, "countTime");
            return (Criteria) this;
        }

        public Criteria andCountTimeLessThanOrEqualTo(Date value) {
            addCriterion("count_time <=", value, "countTime");
            return (Criteria) this;
        }

        public Criteria andCountTimeIn(List<Date> values) {
            addCriterion("count_time in", values, "countTime");
            return (Criteria) this;
        }

        public Criteria andCountTimeNotIn(List<Date> values) {
            addCriterion("count_time not in", values, "countTime");
            return (Criteria) this;
        }

        public Criteria andCountTimeBetween(Date value1, Date value2) {
            addCriterion("count_time between", value1, value2, "countTime");
            return (Criteria) this;
        }

        public Criteria andCountTimeNotBetween(Date value1, Date value2) {
            addCriterion("count_time not between", value1, value2, "countTime");
            return (Criteria) this;
        }

        public Criteria andLevel0SumIsNull() {
            addCriterion("level_0_sum is null");
            return (Criteria) this;
        }

        public Criteria andLevel0SumIsNotNull() {
            addCriterion("level_0_sum is not null");
            return (Criteria) this;
        }

        public Criteria andLevel0SumEqualTo(Integer value) {
            addCriterion("level_0_sum =", value, "level0Sum");
            return (Criteria) this;
        }

        public Criteria andLevel0SumNotEqualTo(Integer value) {
            addCriterion("level_0_sum <>", value, "level0Sum");
            return (Criteria) this;
        }

        public Criteria andLevel0SumGreaterThan(Integer value) {
            addCriterion("level_0_sum >", value, "level0Sum");
            return (Criteria) this;
        }

        public Criteria andLevel0SumGreaterThanOrEqualTo(Integer value) {
            addCriterion("level_0_sum >=", value, "level0Sum");
            return (Criteria) this;
        }

        public Criteria andLevel0SumLessThan(Integer value) {
            addCriterion("level_0_sum <", value, "level0Sum");
            return (Criteria) this;
        }

        public Criteria andLevel0SumLessThanOrEqualTo(Integer value) {
            addCriterion("level_0_sum <=", value, "level0Sum");
            return (Criteria) this;
        }

        public Criteria andLevel0SumIn(List<Integer> values) {
            addCriterion("level_0_sum in", values, "level0Sum");
            return (Criteria) this;
        }

        public Criteria andLevel0SumNotIn(List<Integer> values) {
            addCriterion("level_0_sum not in", values, "level0Sum");
            return (Criteria) this;
        }

        public Criteria andLevel0SumBetween(Integer value1, Integer value2) {
            addCriterion("level_0_sum between", value1, value2, "level0Sum");
            return (Criteria) this;
        }

        public Criteria andLevel0SumNotBetween(Integer value1, Integer value2) {
            addCriterion("level_0_sum not between", value1, value2, "level0Sum");
            return (Criteria) this;
        }

        public Criteria andLevel1SumIsNull() {
            addCriterion("level_1_sum is null");
            return (Criteria) this;
        }

        public Criteria andLevel1SumIsNotNull() {
            addCriterion("level_1_sum is not null");
            return (Criteria) this;
        }

        public Criteria andLevel1SumEqualTo(Integer value) {
            addCriterion("level_1_sum =", value, "level1Sum");
            return (Criteria) this;
        }

        public Criteria andLevel1SumNotEqualTo(Integer value) {
            addCriterion("level_1_sum <>", value, "level1Sum");
            return (Criteria) this;
        }

        public Criteria andLevel1SumGreaterThan(Integer value) {
            addCriterion("level_1_sum >", value, "level1Sum");
            return (Criteria) this;
        }

        public Criteria andLevel1SumGreaterThanOrEqualTo(Integer value) {
            addCriterion("level_1_sum >=", value, "level1Sum");
            return (Criteria) this;
        }

        public Criteria andLevel1SumLessThan(Integer value) {
            addCriterion("level_1_sum <", value, "level1Sum");
            return (Criteria) this;
        }

        public Criteria andLevel1SumLessThanOrEqualTo(Integer value) {
            addCriterion("level_1_sum <=", value, "level1Sum");
            return (Criteria) this;
        }

        public Criteria andLevel1SumIn(List<Integer> values) {
            addCriterion("level_1_sum in", values, "level1Sum");
            return (Criteria) this;
        }

        public Criteria andLevel1SumNotIn(List<Integer> values) {
            addCriterion("level_1_sum not in", values, "level1Sum");
            return (Criteria) this;
        }

        public Criteria andLevel1SumBetween(Integer value1, Integer value2) {
            addCriterion("level_1_sum between", value1, value2, "level1Sum");
            return (Criteria) this;
        }

        public Criteria andLevel1SumNotBetween(Integer value1, Integer value2) {
            addCriterion("level_1_sum not between", value1, value2, "level1Sum");
            return (Criteria) this;
        }

        public Criteria andLevel2SumIsNull() {
            addCriterion("level_2_sum is null");
            return (Criteria) this;
        }

        public Criteria andLevel2SumIsNotNull() {
            addCriterion("level_2_sum is not null");
            return (Criteria) this;
        }

        public Criteria andLevel2SumEqualTo(Integer value) {
            addCriterion("level_2_sum =", value, "level2Sum");
            return (Criteria) this;
        }

        public Criteria andLevel2SumNotEqualTo(Integer value) {
            addCriterion("level_2_sum <>", value, "level2Sum");
            return (Criteria) this;
        }

        public Criteria andLevel2SumGreaterThan(Integer value) {
            addCriterion("level_2_sum >", value, "level2Sum");
            return (Criteria) this;
        }

        public Criteria andLevel2SumGreaterThanOrEqualTo(Integer value) {
            addCriterion("level_2_sum >=", value, "level2Sum");
            return (Criteria) this;
        }

        public Criteria andLevel2SumLessThan(Integer value) {
            addCriterion("level_2_sum <", value, "level2Sum");
            return (Criteria) this;
        }

        public Criteria andLevel2SumLessThanOrEqualTo(Integer value) {
            addCriterion("level_2_sum <=", value, "level2Sum");
            return (Criteria) this;
        }

        public Criteria andLevel2SumIn(List<Integer> values) {
            addCriterion("level_2_sum in", values, "level2Sum");
            return (Criteria) this;
        }

        public Criteria andLevel2SumNotIn(List<Integer> values) {
            addCriterion("level_2_sum not in", values, "level2Sum");
            return (Criteria) this;
        }

        public Criteria andLevel2SumBetween(Integer value1, Integer value2) {
            addCriterion("level_2_sum between", value1, value2, "level2Sum");
            return (Criteria) this;
        }

        public Criteria andLevel2SumNotBetween(Integer value1, Integer value2) {
            addCriterion("level_2_sum not between", value1, value2, "level2Sum");
            return (Criteria) this;
        }

        public Criteria andLevel3SumIsNull() {
            addCriterion("level_3_sum is null");
            return (Criteria) this;
        }

        public Criteria andLevel3SumIsNotNull() {
            addCriterion("level_3_sum is not null");
            return (Criteria) this;
        }

        public Criteria andLevel3SumEqualTo(Integer value) {
            addCriterion("level_3_sum =", value, "level3Sum");
            return (Criteria) this;
        }

        public Criteria andLevel3SumNotEqualTo(Integer value) {
            addCriterion("level_3_sum <>", value, "level3Sum");
            return (Criteria) this;
        }

        public Criteria andLevel3SumGreaterThan(Integer value) {
            addCriterion("level_3_sum >", value, "level3Sum");
            return (Criteria) this;
        }

        public Criteria andLevel3SumGreaterThanOrEqualTo(Integer value) {
            addCriterion("level_3_sum >=", value, "level3Sum");
            return (Criteria) this;
        }

        public Criteria andLevel3SumLessThan(Integer value) {
            addCriterion("level_3_sum <", value, "level3Sum");
            return (Criteria) this;
        }

        public Criteria andLevel3SumLessThanOrEqualTo(Integer value) {
            addCriterion("level_3_sum <=", value, "level3Sum");
            return (Criteria) this;
        }

        public Criteria andLevel3SumIn(List<Integer> values) {
            addCriterion("level_3_sum in", values, "level3Sum");
            return (Criteria) this;
        }

        public Criteria andLevel3SumNotIn(List<Integer> values) {
            addCriterion("level_3_sum not in", values, "level3Sum");
            return (Criteria) this;
        }

        public Criteria andLevel3SumBetween(Integer value1, Integer value2) {
            addCriterion("level_3_sum between", value1, value2, "level3Sum");
            return (Criteria) this;
        }

        public Criteria andLevel3SumNotBetween(Integer value1, Integer value2) {
            addCriterion("level_3_sum not between", value1, value2, "level3Sum");
            return (Criteria) this;
        }

        public Criteria andLevel4SumIsNull() {
            addCriterion("level_4_sum is null");
            return (Criteria) this;
        }

        public Criteria andLevel4SumIsNotNull() {
            addCriterion("level_4_sum is not null");
            return (Criteria) this;
        }

        public Criteria andLevel4SumEqualTo(Integer value) {
            addCriterion("level_4_sum =", value, "level4Sum");
            return (Criteria) this;
        }

        public Criteria andLevel4SumNotEqualTo(Integer value) {
            addCriterion("level_4_sum <>", value, "level4Sum");
            return (Criteria) this;
        }

        public Criteria andLevel4SumGreaterThan(Integer value) {
            addCriterion("level_4_sum >", value, "level4Sum");
            return (Criteria) this;
        }

        public Criteria andLevel4SumGreaterThanOrEqualTo(Integer value) {
            addCriterion("level_4_sum >=", value, "level4Sum");
            return (Criteria) this;
        }

        public Criteria andLevel4SumLessThan(Integer value) {
            addCriterion("level_4_sum <", value, "level4Sum");
            return (Criteria) this;
        }

        public Criteria andLevel4SumLessThanOrEqualTo(Integer value) {
            addCriterion("level_4_sum <=", value, "level4Sum");
            return (Criteria) this;
        }

        public Criteria andLevel4SumIn(List<Integer> values) {
            addCriterion("level_4_sum in", values, "level4Sum");
            return (Criteria) this;
        }

        public Criteria andLevel4SumNotIn(List<Integer> values) {
            addCriterion("level_4_sum not in", values, "level4Sum");
            return (Criteria) this;
        }

        public Criteria andLevel4SumBetween(Integer value1, Integer value2) {
            addCriterion("level_4_sum between", value1, value2, "level4Sum");
            return (Criteria) this;
        }

        public Criteria andLevel4SumNotBetween(Integer value1, Integer value2) {
            addCriterion("level_4_sum not between", value1, value2, "level4Sum");
            return (Criteria) this;
        }

        public Criteria andCountTypeIsNull() {
            addCriterion("count_type is null");
            return (Criteria) this;
        }

        public Criteria andCountTypeIsNotNull() {
            addCriterion("count_type is not null");
            return (Criteria) this;
        }

        public Criteria andCountTypeEqualTo(String value) {
            addCriterion("count_type =", value, "countType");
            return (Criteria) this;
        }

        public Criteria andCountTypeNotEqualTo(String value) {
            addCriterion("count_type <>", value, "countType");
            return (Criteria) this;
        }

        public Criteria andCountTypeGreaterThan(String value) {
            addCriterion("count_type >", value, "countType");
            return (Criteria) this;
        }

        public Criteria andCountTypeGreaterThanOrEqualTo(String value) {
            addCriterion("count_type >=", value, "countType");
            return (Criteria) this;
        }

        public Criteria andCountTypeLessThan(String value) {
            addCriterion("count_type <", value, "countType");
            return (Criteria) this;
        }

        public Criteria andCountTypeLessThanOrEqualTo(String value) {
            addCriterion("count_type <=", value, "countType");
            return (Criteria) this;
        }

        public Criteria andCountTypeLike(String value) {
            addCriterion("count_type like", value, "countType");
            return (Criteria) this;
        }

        public Criteria andCountTypeNotLike(String value) {
            addCriterion("count_type not like", value, "countType");
            return (Criteria) this;
        }

        public Criteria andCountTypeIn(List<String> values) {
            addCriterion("count_type in", values, "countType");
            return (Criteria) this;
        }

        public Criteria andCountTypeNotIn(List<String> values) {
            addCriterion("count_type not in", values, "countType");
            return (Criteria) this;
        }

        public Criteria andCountTypeBetween(String value1, String value2) {
            addCriterion("count_type between", value1, value2, "countType");
            return (Criteria) this;
        }

        public Criteria andCountTypeNotBetween(String value1, String value2) {
            addCriterion("count_type not between", value1, value2, "countType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table alert_level_statistics
     *
     * @mbg.generated do_not_delete_during_merge Fri Aug 17 11:45:47 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table alert_level_statistics
     *
     * @mbg.generated Fri Aug 17 11:45:47 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}